# Generated by Django 5.1.1 on 2025-01-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rent',
            field=models.IntegerField(),
        ),
    ]
