# Generated by Django 5.1.1 on 2025-01-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_user'),
        ('driver', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Completed', 'Complete'), ('Pending', 'Pending'), ('Running', 'Running')], max_length=20)),
                ('types', models.CharField(choices=[('Car', 'Car'), ('Taxi', 'Taxi'), ('Bike', 'Bike')], max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('geolocation', models.CharField(max_length=50)),
                ('cancel', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
