# Generated by Django 5.1.1 on 2025-01-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_review'),
        ('vehicle', '0002_remove_riderrequest_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='driver/images')),
                ('registration_number', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
            ],
        ),
    ]
